### ISSUE TITLE
support assignment

### ISSUE THREAD

**Issue by Arinerron** [Arinerron/smartbytes#1]
```
>>> a = smartbytes('asdf')
>>> a[2] = 's'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'smartbytes' object does not support item assignment
```

**Comment by Arinerron** [comment]
```
>>> list(smartbytes('asfd'))
[b'a', b's', b'f', b'd']
>>> a=list(smartbytes('asfd'))
>>> a[2]=b'asdf'
>>> smartbytes(a)
b'asasdfd'
```

**Comment by Arinerron** [comment]
```
>>> a[3:4]='d'
warning: cannot convert value slice(0, slic
e(3, 4, None), None) of type <class 'slice'> to bytes
Traceback (most recent call last):
  File "/home/aaron/github/smartbytes/smartbytes/smartbytes.py", line 422, in __getitem__
    return smartbytes(self.get_contents().__getitem__(key, *args, **kwargs))
TypeError: slice indices must be integers or None or have an __index__ method

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aaron/github/smartbytes/smartbytes/smartbytes.py", line 429, in __setitem__
    self.contents = bytes(self[0:key] + smartbytes(value) + self[key+1+(0 if length == None else length):len(self)])
  File "/home/aaron/github/smartbytes/smartbytes/smartbytes.py", line 425, in __getitem__
    return self.find(key, *args, **kwargs)
  File "/home/aaron/github/smartbytes/smartbytes/smartbytes.py", line 412, in find
    key = smartbytes(key)
  File "/home/aaron/github/smartbytes/smartbytes/smartbytes.py", line 198, in __init__
    self.contents = self._to_bytes(contents)
  File "/home/aaron/github/smartbytes/smartbytes/smartbytes.py", line 224, in _to_bytes
    return to_bytes(value, endian = endian, encoding = encoding)
  File "/home/aaron/github/smartbytes/smartbytes/smartbytes.py", line 72, in to_bytes
    raise TypeError
TypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aaron/github/smartbytes/smartbytes/smartbytes.py", line 432, in __setitem__
    self.__setitem__(self[key], value, length = (len(key) if length == None else length))
TypeError: object of type 'slice' has no len()
```
